### ISSUE TITLE
error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')

### ISSUE THREAD

**Issue by rtentser** [sexcoin-project/sexcoin#17]
It happens when i try to compile sexcoin. I think it was fixed in litecoin and some other coins: [https://github.com/litecoin-project/litecoin/issues/240].

> Making all in src
> make[1]: Entering directory '/home/rtentser/Sources/sexcoin/src'
> make[2]: Entering directory '/home/rtentser/Sources/sexcoin/src'
>   CXX      primitives/libbitcoinconsensus_la-transaction.lo
>   CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
>   CXX      crypto/libbitcoinconsensus_la-scrypt.lo
>   CXX      crypto/libbitcoinconsensus_la-sha1.lo
>   CXX      crypto/libbitcoinconsensus_la-sha256.lo
>   CXX      crypto/libbitcoinconsensus_la-sha512.lo
>   CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
>   CXX      libbitcoinconsensus_la-eccryptoverify.lo
>   CXX      libbitcoinconsensus_la-ecwrapper.lo
>   CXX      libbitcoinconsensus_la-hash.lo
>   CXX      libbitcoinconsensus_la-pubkey.lo
>   CXX      script/libbitcoinconsensus_la-script.lo
>   CXX      script/libbitcoinconsensus_la-interpreter.lo
>   CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo
>   CXX      libbitcoinconsensus_la-uint256.lo
>   CXX      libbitcoinconsensus_la-utilstrencodings.lo
>   CXXLD    libbitcoinconsensus.la
> /usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
>   CXX      sexcoind-bitcoind.o
>   CXX      libbitcoin_server_a-addrman.o
>   CXX      libbitcoin_server_a-alert.o
>   CXX      libbitcoin_server_a-bloom.o
>   CXX      libbitcoin_server_a-chain.o
>   CXX      libbitcoin_server_a-checkpoints.o
>   CXX      libbitcoin_server_a-forkparams.o
>   CXX      libbitcoin_server_a-init.o
>   CXX      libbitcoin_server_a-leveldbwrapper.o
>   CXX      libbitcoin_server_a-main.o
>   CXX      libbitcoin_server_a-merkleblock.o
>   CXX      libbitcoin_server_a-miner.o
> miner.cpp: In function 'CBlockTemplate* CreateNewBlock(const CScript&)':
> miner.cpp:95:5: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
>      auto_ptr<CBlockTemplate> pblocktemplate(new CBlockTemplate());
>      ^~~~~~~~
> In file included from /usr/include/c++/6/memory:81:0,
>                  from /usr/include/boost/unordered/unordered_map_fwd.hpp:14,
>                  from /usr/include/boost/unordered/unordered_map.hpp:17,
>                  from /usr/include/boost/unordered_map.hpp:17,
>                  from coins.h:18,
>                  from main.h:16,
>                  from miner.cpp:13:
> /usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
>    template<typename> class auto_ptr;
>                             ^~~~~~~~
> miner.cpp: In function 'void BitcoinMiner(CWallet*)':
> miner.cpp:444:13: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
>              auto_ptr<CBlockTemplate> pblocktemplate(CreateNewBlockWithKey(reservekey));
>              ^~~~~~~~
> In file included from /usr/include/c++/6/memory:81:0,
>                  from /usr/include/boost/unordered/unordered_map_fwd.hpp:14,
>                  from /usr/include/boost/unordered/unordered_map.hpp:17,
>                  from /usr/include/boost/unordered_map.hpp:17,
>                  from coins.h:18,
>                  from main.h:16,
>                  from miner.cpp:13:
> /usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
>    template<typename> class auto_ptr;
>                             ^~~~~~~~
> At global scope:
> cc1plus: warning: unrecognized command line option '-Wno-self-assign'
>   CXX      libbitcoin_server_a-net.o
>   CXX      libbitcoin_server_a-noui.o
>   CXX      libbitcoin_server_a-pow.o
> pow.cpp: In function 'unsigned int GetNextWorkRequired(const CBlockIndex*, const CBlockHeader*)':
> pow.cpp:237:13: warning: unused variable 'height' [-Wunused-variable]
>      int64_t height = chainActive.Height();
>              ^~~~~~
> pow.cpp:245:13: warning: unused variable 'nTargetSpacing' [-Wunused-variable]
>      int64_t nTargetSpacing = ForkingParams().Spacing(pindexLast->nHeight +1);
>              ^~~~~~~~~~~~~~
> At global scope:
> cc1plus: warning: unrecognized command line option '-Wno-self-assign'
>   CXX      libbitcoin_server_a-rest.o
>   CXX      libbitcoin_server_a-rpcblockchain.o
>   CXX      libbitcoin_server_a-rpcmining.o
> rpcmining.cpp: In function 'json_spirit::Value setgenerate(const Array&, bool)':
> rpcmining.cpp:173:13: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
>              auto_ptr<CBlockTemplate> pblocktemplate(CreateNewBlockWithKey(reservekey));
>              ^~~~~~~~
> In file included from /usr/include/c++/6/memory:81:0,
>                  from /usr/include/boost/config/no_tr1/memory.hpp:21,
>                  from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
>                  from /usr/include/boost/shared_ptr.hpp:17,
>                  from /usr/include/boost/date_time/time_clock.hpp:17,
>                  from /usr/include/boost/thread/thread_time.hpp:9,
>                  from /usr/include/boost/thread/lock_types.hpp:18,
>                  from /usr/include/boost/thread/pthread/mutex.hpp:16,
>                  from /usr/include/boost/thread/mutex.hpp:16,
>                  from allocators.h:14,
>                  from streams.h:9,
>                  from net.h:17,
>                  from rpcmining.cpp:10:
> /usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
>    template<typename> class auto_ptr;
>                             ^~~~~~~~
> At global scope:
> cc1plus: warning: unrecognized command line option '-Wno-self-assign'
>   CXX      libbitcoin_server_a-rpcmisc.o
>   CXX      libbitcoin_server_a-rpcnet.o
>   CXX      libbitcoin_server_a-rpcrawtransaction.o
>   CXX      libbitcoin_server_a-rpcserver.o
>   CXX      script/libbitcoin_server_a-sigcache.o
>   CXX      libbitcoin_server_a-timedata.o
>   CXX      libbitcoin_server_a-txdb.o
>   CXX      libbitcoin_server_a-txmempool.o
>   AR       libbitcoin_server.a
> /usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
>   CXX      libbitcoin_common_a-allocators.o
>   CXX      libbitcoin_common_a-amount.o
>   CXX      libbitcoin_common_a-base58.o
>   CXX      libbitcoin_common_a-chainparams.o
> chainparams.cpp: In constructor 'CMainParams::CMainParams()':
> chainparams.cpp:199:52: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[PUBKEY_ADDRESS] = list_of(62);
>                                                     ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> chainparams.cpp:200:51: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[SCRIPT_ADDRESS] = list_of(5);
>                                                    ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> chainparams.cpp:201:53: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[SECRET_KEY] =     list_of(190);
>                                                      ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> chainparams.cpp:202:72: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[EXT_PUBLIC_KEY] = list_of(0x04)(0x88)(0xB2)(0x1E);
>                                                                         ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> chainparams.cpp:203:72: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[EXT_SECRET_KEY] = list_of(0x04)(0x88)(0xAD)(0xE4);
>                                                                         ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> chainparams.cpp: In constructor 'CTestNetParams::CTestNetParams()':
> chainparams.cpp:283:53: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[PUBKEY_ADDRESS] = list_of(124);
>                                                      ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> chainparams.cpp:284:53: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[SCRIPT_ADDRESS] = list_of(196);
>                                                      ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> chainparams.cpp:285:53: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[SECRET_KEY]     = list_of(239);
>                                                      ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> chainparams.cpp:286:72: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[EXT_PUBLIC_KEY] = list_of(0x04)(0x35)(0x87)(0xCF);
>                                                                         ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> chainparams.cpp:287:72: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
>          base58Prefixes[EXT_SECRET_KEY] = list_of(0x04)(0x35)(0x83)(0x94);
>                                                                         ^
> In file included from /usr/include/c++/6/vector:69:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6/vector:64:0,
>                  from chainparamsbase.h:9,
>                  from chainparams.h:9,
>                  from chainparams.cpp:6:
> /usr/include/c++/6/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> At global scope:
> cc1plus: warning: unrecognized command line option '-Wno-self-assign'
> Makefile:3174: recipe for target 'libbitcoin_common_a-chainparams.o' failed
> make[2]: *** [libbitcoin_common_a-chainparams.o] Error 1
> make[2]: Leaving directory '/home/rtentser/Sources/sexcoin/src'
> Makefile:6348: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/rtentser/Sources/sexcoin/src'
> Makefile:573: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

**Comment by bitspill** [comment]
That's an issue with newer C++11 versions, to fix replace 

```
        base58Prefixes[PUBKEY_ADDRESS] = list_of(62);
        base58Prefixes[SCRIPT_ADDRESS] = list_of(5);
        base58Prefixes[SECRET_KEY] =     list_of(190);
        base58Prefixes[EXT_PUBLIC_KEY] = list_of(0x04)(0x88)(0xB2)(0x1E);
        base58Prefixes[EXT_SECRET_KEY] = list_of(0x04)(0x88)(0xAD)(0xE4);
```


With


```
base58Prefixes[PUBKEY_ADDRESS] = {62};
base58Prefixes[SCRIPT_ADDRESS] = {5};
base58Prefixes[SECRET_KEY] =     {190};
base58Prefixes[EXT_PUBLIC_KEY] = {0x04,0x88,0xB2,0x1E};
base58Prefixes[EXT_SECRET_KEY] = {0x04,0x88,0xAD,0xE4};
```

**Comment by rtentser** [comment]
There is some other lines that needs a similar fix. And it works. Thank you.

**Comment by lavajumper** [comment]
We've got most of these fixes on our development repositories. We need to get these pushed up. 
Will keep this open until the fix is committed.

**Comment by sexcoin-project** [comment]
Fixed in 15 ... closing
